---
# roles/repositories/vars/catalog.yml
# This is the internal catalog defining how each repository type should be created in Nexus.

repo_catalog:
  docker_hub:
    format: "docker"
    type: "proxy"
    api_payload:
      name: "docker-proxy-hub"
      online: true
      storage:
        blobStoreName: "default"
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "https://registry-1.docker.io"
        contentMaxAge: 1440
        metadataMaxAge: 1440
      docker:
        v1Enabled: false
        forceBasicAuth: true
      dockerProxy:
        indexType: "REGISTRY"

  maven_central:
    format: "maven2"
    type: "proxy"
    api_payload:
      name: "maven-proxy-central"
      online: true
      storage:
        blobStoreName: "default"
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "https://repo1.maven.org/maven2/"
        contentMaxAge: 1440
        metadataMaxAge: 1440
      maven:
        versionPolicy: "RELEASE"
        layoutPolicy: "PERMISSIVE"

  npm_registry:
    format: "npm"
    type: "proxy"
    api_payload:
      name: "npm-proxy-registry"
      online: true
      storage:
        blobStoreName: "default"
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "https://registry.npmjs.org/"
        contentMaxAge: 1440
        metadataMaxAge: 1440

  pypi_org:
    format: "pypi"
    type: "proxy"
    api_payload:
      name: "pypi-proxy-org"
      online: true
      storage:
        blobStoreName: "default"
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "https://pypi.org/"
        contentMaxAge: 1440
        metadataMaxAge: 1440
