---
# roles/repositories/tasks/main.yml

- name: Load Repository Catalog
  ansible.builtin.include_vars:
    file: catalog.yml
    name: loaded_catalog

- name: Get list of existing repositories from Nexus
  ansible.builtin.uri:
    url: "http://localhost:{{ nexus.http_port | default(8081) }}/service/rest/v1/repositories"
    method: GET
    user: "{{ nexus.admin_user | default('admin') }}"
    password: "{{ nexus.admin_password }}"
    force_basic_auth: true
    return_content: true
    status_code: 200
  register: existing_repos_api
  no_log: true
  changed_when: false

- name: Set fact for existing repository names
  ansible.builtin.set_fact:
    existing_repo_names: "{{ existing_repos_api.json | map(attribute='name') | list }}"

- name: Manage individual repositories
  ansible.builtin.include_tasks: manage_repo.yml
  loop: "{{ repositories | dict2items }}"
  loop_control:
    loop_var: repo_item
    label: "{{ repo_item.key }}"
  # Only process if 'enabled' is set to true
  when: repo_item.value.enabled | default(false) | bool
