---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nexus-repos-test
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    docker_networks:
      - name: nexus-test
        driver: bridge
    networks:
      - name: nexus-test
    published_ports:
      - "8081:8081"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        nexus_admin_password: admin123
        nexus_port: 8081
        nexus_repos: []
        nexus_repos_delete_unmanaged: false
        nexus_repos_expected: []
        nexus_api_retries: 3
        nexus_api_retry_delay: 5
        nexus_repos_run_once: false
        nexus_no_log: true
verifier:
  name: ansible
